lastChangelogVersion: 13.17.0
modelRoles: 
  smol: github-copilot/gpt-5.4-mini:high
  default: openai-codex/gpt-5.4
  slow: openai-codex/gpt-5.4:high
  commit: openai-codex/gpt-5.3-codex-spark:medium
  plan: openai-codex/gpt-5.4:xhigh
  task: openai-codex/gpt-5.4:medium
  vision: google-vertex/gemini-3-flash-preview:medium
theme: 
  dark: dark-catppuccin
symbolPreset: nerd
todo: 
  reminders: true
  enabled: true
defaultThinkingLevel: high
collapseChangelog: true
disabledExtensions: 
  - mcp:call-me
  - mcp:serena
extensions: 
  - /Users/alexanderbutler/code_projects/pi-loom
disabledProviders: 
  - claude-plugins
  - opencode
  - codex
browser: 
  headless: false
steeringMode: all
followUpMode: one-at-a-time
interruptMode: wait
bash: 
  virtualTerminal: "off"
compaction: 
  thresholdPercent: 70
  handoffSaveToDisk: true
memories: 
  enabled: false
edit: 
  mode: patch
readHashLines: false
async: 
  enabled: true
commands: 
  enableClaudeUser: false
  enableClaudeProject: false
task: 
  eager: false
  isolation: 
    mode: none
    merge: patch
    commits: ai
terminal: 
  showImages: false
startup: 
  quiet: true
ttsr: 
  enabled: false
contextPromotion: 
  enabled: false
bashInterceptor: 
  simpleLs: false
renderMermaid: 
  enabled: true
astGrep: 
  enabled: true
astEdit: 
  enabled: false
hideThinkingBlock: false