# https://alacritty.org/config-alacritty.html

import = []

shell = { program = "/bin/bash", args = ["-lic", "tmux new -As0"] }

live_config_reload = true
ipc_socket = true

env.TERM = "xterm-256color"
env.EDITOR = "nvim"
env.VISUAL = "nvim"
env.PAGER = "less"
env.MANPAGER = "nvim +\"silent! runtime plugin/man.lua | Man!\""
env.CLICOLOR = "1"
env.LSCOLORS = "ExFxBxDxCxegedabagacad"

[window]
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.9
blur = true
startup_mode = "SimpleFullscreen"
option_as_alt = "OnlyLeft"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold_italic = { family = "VictorMono Nerd Font", style = "Bold Italic" }

size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
# Mouse bindings (actual bindings need to be defined as per user preference)
# Example: bindings = [{ mouse = "Left", action = "Paste" }]
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

[keyboard]
bindings = [
  { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
  { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
  { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
  { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
  { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
  { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
  { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
  { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
  { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
  { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
  { key = "Return", mods = "Control", chars = "\u001b[13;5u" },
  { key = "Backspace", mods = "Control", chars = "\u001b[127;5u" },
]
